# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_personal', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=200)),
                ('curp', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=20)),
                ('edo_civil', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=100)),
                ('otra_red', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=200)),
                ('hra_entrada', models.DateTimeField()),
                ('hra_salida', models.DateTimeField()),
                ('fech_engreso', models.DateField()),
            ],
        ),
    ]
