# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granjasalmoral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopersonal',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
