# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granjasalmoral', '0002_infopersonal_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopersonal',
            name='img',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
