# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 19:43
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granjasalmoral', '0003_infopersonal_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_salida', models.CharField(max_length=100)),
                ('lugar_destino', models.CharField(max_length=100)),
                ('distancia', models.CharField(max_length=50)),
                ('vehiculo', models.CharField(max_length=50)),
                ('fecha_orden', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fech_actual', models.DateField()),
                ('hra_in', models.TimeField()),
                ('hra_out', models.TimeField()),
                ('retardo', models.BooleanField()),
                ('justificado', models.BooleanField()),
                ('comision_personal', models.BooleanField()),
                ('lugar_trabajo', models.CharField(max_length=200)),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='justificante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_justificante', models.DateField()),
                ('tiempo', models.TimeField()),
                ('soporte', models.FileField(default='', upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=50)),
                ('cantidad_ini', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cantidad_rest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('plazo', models.IntegerField()),
                ('letras_pagos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('fecha_prest', models.DateField()),
                ('pagare', models.FileField(default='', upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='infopersonal',
            name='fech_engreso',
        ),
        migrations.AddField(
            model_name='infopersonal',
            name='fech_ingreso_cooperativa',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='infopersonal',
            name='fech_ingreso_empresa',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='infopersonal',
            name='pwd_personal',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='infopersonal',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='infopersonal',
            name='hra_entrada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='infopersonal',
            name='hra_salida',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='granjasalmoral.InfoPersonal'),
        ),
        migrations.AddField(
            model_name='justificante',
            name='id_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='granjasalmoral.InfoPersonal'),
        ),
        migrations.AddField(
            model_name='jornada',
            name='id_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='granjasalmoral.InfoPersonal'),
        ),
        migrations.AddField(
            model_name='comision',
            name='id_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='granjasalmoral.InfoPersonal'),
        ),
    ]
