# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granjasalmoral', '0008_auto_20160929_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopersonal',
            name='fech_ingreso_cooperativa',
            field=models.DateField(blank=True, default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='infopersonal',
            name='fech_ingreso_empresa',
            field=models.DateField(blank=True, default='0000-00-00'),
        ),
    ]
