# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granjasalmoral', '0009_auto_20160929_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopersonal',
            name='fech_ingreso_cooperativa',
        ),
        migrations.RemoveField(
            model_name='infopersonal',
            name='fech_ingreso_empresa',
        ),
    ]
