# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granjasalmoral', '0012_auto_20160929_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=50)),
                ('apoderado', models.CharField(max_length=50)),
                ('direccion', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='comision',
            name='fecha_orden',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infopersonal',
            name='id_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='granjasalmoral.empresas'),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='fech_actual',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hra_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='hra_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='justificante',
            name='fecha_justificante',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='justificante',
            name='tiempo',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prest',
            field=models.DateField(blank=True, null=True),
        ),
    ]
