# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granjasalmoral', '0013_auto_20161001_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopersonal',
            name='hra_entrada',
        ),
        migrations.RemoveField(
            model_name='infopersonal',
            name='hra_salida',
        ),
        migrations.RemoveField(
            model_name='jornada',
            name='hra_in',
        ),
        migrations.RemoveField(
            model_name='jornada',
            name='hra_out',
        ),
    ]
