# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('granjasalmoral', '0014_auto_20161001_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='fecha_orden',
        ),
        migrations.RemoveField(
            model_name='infopersonal',
            name='fech_ingreso_cooperativa',
        ),
        migrations.RemoveField(
            model_name='infopersonal',
            name='fech_ingreso_empresa',
        ),
        migrations.RemoveField(
            model_name='jornada',
            name='fech_actual',
        ),
        migrations.RemoveField(
            model_name='justificante',
            name='fecha_justificante',
        ),
        migrations.RemoveField(
            model_name='justificante',
            name='tiempo',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='fecha_prest',
        ),
    ]
