# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granjasalmoral', '0016_auto_20161001_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopersonal',
            name='id_personal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
