# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 05:23
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granjasalmoral', '0019_auto_20161001_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_salida', models.CharField(max_length=100)),
                ('lugar_destino', models.CharField(max_length=100)),
                ('distancia', models.CharField(max_length=50)),
                ('vehiculo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InfoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_personal', models.CharField(blank=True, max_length=30, null=True)),
                ('pwd_personal', models.CharField(default='', max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=200)),
                ('curp', models.CharField(max_length=50)),
                ('rfc', models.CharField(max_length=30)),
                ('edad', models.IntegerField(default=0)),
                ('genero', models.CharField(max_length=20)),
                ('edo_civil', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=100)),
                ('otra_red', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=200)),
                ('sueldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('img', models.FileField(null=True, upload_to='uploads/')),
                ('razon_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='granjasalmoral.empresas')),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retardo', models.BooleanField()),
                ('justificado', models.BooleanField()),
                ('comision_personal', models.BooleanField()),
                ('lugar_trabajo', models.CharField(max_length=200)),
                ('observacion', models.TextField()),
                ('id_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='granjasalmoral.InfoPersonal')),
            ],
        ),
        migrations.CreateModel(
            name='justificante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('soporte', models.FileField(null=True, upload_to='uploads/')),
                ('id_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='granjasalmoral.InfoPersonal')),
            ],
        ),
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=50)),
                ('cantidad_ini', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('cantidad_rest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('plazo', models.IntegerField()),
                ('letras_pagos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('pagare', models.FileField(null=True, upload_to='uploads/')),
                ('id_personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='granjasalmoral.InfoPersonal')),
            ],
        ),
        migrations.AddField(
            model_name='comision',
            name='id_personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='granjasalmoral.InfoPersonal'),
        ),
    ]
